# Fast Batch Multitask Lattice GP

In [1]:
import fastgp
import torch
import numpy as np

In [2]:
torch.set_default_dtype(torch.float64)

## True Function

In [3]:
def f(l,x):
    weights = 2**torch.arange(1,l+2)
    return torch.vstack([
        (torch.sin(weights*np.pi*x)/weights).sum(1),
        (torch.cos(weights*np.pi*x)/weights).sum(1),
    ])
num_tasks = 4
d = 1 # dimension
rng = torch.Generator().manual_seed(17)
x = torch.rand((2**7,d),generator=rng) # random testing locations
y = torch.cat([f(l,x)[:,None,:] for l in range(num_tasks)],1) # true values at random testing locations
z = torch.rand((2**8,d),generator=rng) # other random locations at which to evaluate covariance
print("x.shape = %s"%str(tuple(x.shape)))
print("y.shape = %s"%str(tuple(y.shape)))
print("z.shape = %s"%str(tuple(z.shape)))

x.shape = (128, 1)
y.shape = (2, 4, 128)
z.shape = (256, 1)


## Construct Fast GP

In [4]:
fgp = fastgp.FastGPLattice(d,seed_for_seq=7,num_tasks=num_tasks)
x_next = fgp.get_x_next(n=2**torch.arange(5,5+num_tasks))
y_next = [f(l,x_next[l]) for l in range(num_tasks)]
fgp.add_y_next(y_next)
assert len(x_next)==len(y_next)
for i in range(len(x_next)):
    print("i = %d"%i)
    print("\tx_next[%d].shape = %s"%(i,str(tuple(x_next[i].shape))))
    print("\ty_next[%d].shape = %s"%(i,str(tuple(y_next[i].shape))))

i = 0
	x_next[0].shape = (32, 1)
	y_next[0].shape = (2, 32)
i = 1
	x_next[1].shape = (64, 1)
	y_next[1].shape = (2, 64)
i = 2
	x_next[2].shape = (128, 1)
	y_next[2].shape = (2, 128)
i = 3
	x_next[3].shape = (256, 1)
	y_next[3].shape = (2, 256)


In [5]:
pmean = fgp.post_mean(x)
print("pmean.shape = %s"%str(tuple(pmean.shape)))
print("l2 relative error:\n%s"%str(torch.linalg.norm(y-pmean,dim=-1)/torch.linalg.norm(y,dim=-1)))

pmean.shape = (2, 4, 128)
l2 relative error:
tensor([[6.0040e-04, 3.8550e-05, 3.2118e-06, 5.6326e-07],
        [6.3219e-04, 3.5825e-05, 2.6625e-06, 6.6222e-07]])


In [6]:
data = fgp.fit()
list(data.keys())

     iter of 5.0e+03 | NMLL       | noise      | scale      | lengthscales         | task_kernel 
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            0.00e+00 | -9.10e+04  | 1.00e-08   | 1.00e+00   | [1.0e+00]            | [[2.0e+00 1.0e+00 1.0e+00 1.0e+00] [1.0e+00 2.0e+00 1.0e+00 1.0e+00] [1.0e+00 1.0e+00 2.0e+00 1.0e+00] [1.0e+00 1.0e+00 1.0e+00 2.0e+00]]
            5.00e+00 | -1.31e+05  | 1.00e-08   | 4.75e-01   | [4.8e-01]            | [[5.4e-01 6.5e-02 6.5e-02 6.5e-02] [6.5e-02 5.4e-01 6.5e-02 6.5e-02] [6.5e-02 6.5e-02 5.4e-01 6.5e-02] [6.5e-02 6.5e-02 6.5e-02 5.4e-01]]
            1.00e+01 | -1.67e+05  | 1.00e-08   | 7.46e-02   | [7.5e-02]            | [[7.6e-02 1.4e-03 1.4e-03 -5.2e-03] [1.4e-03 7.6e-02 1.4e-03 -5.2e-03] [1.4e-03 1.4e-03 7.6e-02 -5.2e-03] [-5.2e-03 -5.2e-03 -5.2e-03 1.5e-01]]
            1.50e+01 | -1.83e+05  | 1.00e-08   | 1.13e-01   | [1.1e-01]            | [[1.3e-02 8.4e-04 8.4e-04 1.6e-03] [8.4e-04 

['mll_hist', 'scale_hist', 'lengthscales_hist', 'task_kernel_hist']

In [7]:
pmean,pvar,q,ci_low,ci_high = fgp.post_ci(x,confidence=0.99)
print("pmean.shape = %s"%str(tuple(pmean.shape)))
print("pvar.shape = %s"%str(tuple(pvar.shape)))
print("q = %.2f"%q)
print("ci_low.shape = %s"%str(tuple(ci_low.shape)))
print("ci_high.shape = %s"%str(tuple(ci_high.shape)))
print("l2 relative error:\n%s"%str(torch.linalg.norm(y-pmean,dim=-1)/torch.linalg.norm(y,dim=-1)))
pcov = fgp.post_cov(x,x)
print("pcov.shape = %s"%str(tuple(pcov.shape)))
_range0,_rangen1 = torch.arange(pcov.size(0)),torch.arange(pcov.size(-1))
assert torch.allclose(pcov[_range0,_range0][:,_rangen1,_rangen1],pvar) and (pvar>=0).all()
pcov2 = fgp.post_cov(x,z)
print("pcov2.shape = %s"%str(tuple(pcov2.shape)))

pmean.shape = (2, 4, 128)
pvar.shape = (4, 128)
q = 2.58
ci_low.shape = (2, 4, 128)
ci_high.shape = (2, 4, 128)
l2 relative error:
tensor([[9.7381e-06, 2.5213e-06, 1.3903e-06, 4.6685e-07],
        [1.1162e-05, 2.7929e-06, 1.3616e-06, 5.0744e-07]])
pcov.shape = (4, 4, 128, 128)
pcov2.shape = (4, 4, 128, 256)


In [8]:
pcmean,pcvar,q,cci_low,cci_high = fgp.post_cubature_ci(confidence=0.99)
print("pcmean:\n%s"%str(pcmean))
print("\npcvar:\n%s"%str(pcvar))
print("\ncci_low:\n%s"%str(cci_low))
print("\ncci_high:\n%s"%str(cci_high))

pcmean:
tensor([[-6.4477e-19, -1.7580e-18, -1.2357e-17,  4.0959e-18],
        [ 5.1969e-19,  2.2953e-18,  9.7279e-18, -2.6348e-17]])

pcvar:
tensor([6.9282e-13, 1.4658e-12, 2.1820e-12, 1.1276e-12])

cci_low:
tensor([[-2.1440e-06, -3.1186e-06, -3.8049e-06, -2.7352e-06],
        [-2.1440e-06, -3.1186e-06, -3.8049e-06, -2.7352e-06]])

cci_high:
tensor([[2.1440e-06, 3.1186e-06, 3.8049e-06, 2.7352e-06],
        [2.1440e-06, 3.1186e-06, 3.8049e-06, 2.7352e-06]])


## Project and Increase Sample Size

In [9]:
n_new = fgp.n*2**torch.arange(num_tasks-1,-1,-1)
pcov_future = fgp.post_cov(x,z,n=n_new)
pvar_future = fgp.post_var(x,n=n_new)
pcvar_future = fgp.post_cubature_var(n=n_new)

In [10]:
x_next = fgp.get_x_next(n_new)
y_next = [f(l,x_next[l]) for l in range(num_tasks)]
for _y in y_next:
    print(_y.shape)
fgp.add_y_next(y_next)
print("l2 relative error:\n%s"%str(torch.linalg.norm(y-fgp.post_mean(x),dim=-1)/torch.linalg.norm(y,dim=-1)))
assert torch.allclose(fgp.post_cov(x,z),pcov_future)
assert torch.allclose(fgp.post_var(x),pvar_future)
assert torch.allclose(fgp.post_cubature_var(),pcvar_future)

torch.Size([2, 224])
torch.Size([2, 192])
torch.Size([2, 128])
torch.Size([2, 0])
l2 relative error:
tensor([[5.3823e-09, 2.5754e-08, 9.4975e-08, 3.5826e-07],
        [5.2500e-09, 3.0060e-08, 1.1411e-07, 3.3174e-07]])


In [11]:
data = fgp.fit(verbose=False,store_mll_hist=False,store_scale_hist=False,store_lengthscales_hist=False,store_noise_hist=False)
print("l2 relative error:\n%s"%str(torch.linalg.norm(y-fgp.post_mean(x),dim=-1)/torch.linalg.norm(y,dim=-1)))

l2 relative error:
tensor([[5.6225e-09, 2.8592e-08, 7.4030e-08, 3.6248e-07],
        [5.6828e-09, 3.3488e-08, 8.9043e-08, 3.3699e-07]])


In [12]:
n_new = fgp.n*2**torch.arange(num_tasks)
pcov_new = fgp.post_cov(x,z,n=n_new)
pvar_new = fgp.post_var(x,n=n_new)
pcvar_new = fgp.post_cubature_var(n=n_new)
x_next = fgp.get_x_next(n_new)
y_next = [f(l,x_next[l]) for l in range(num_tasks)]
fgp.add_y_next(y_next)
assert torch.allclose(fgp.post_cov(x,z),pcov_new)
assert torch.allclose(fgp.post_var(x),pvar_new)
assert torch.allclose(fgp.post_cubature_var(),pcvar_new)